### ISSUE TITLE
Suddenly, this error.

### ISSUE THREAD

**Issue by Deckard9999** [receyuki/stable-diffusion-prompt-reader#17]
I set the whitelist on ESET but still:

Traceback (most recent call last):
  File "requests\compat.py", line 11, in <module>
ModuleNotFoundError: No module named 'chardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "app.py", line 21, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "update_checker.py", line 9, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "requests\__init__.py", line 45, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "requests\exceptions.py", line 9, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "requests\compat.py", line 13, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "charset_normalizer\__init__.py", line 24, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "charset_normalizer\api.py", line 5, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "charset_normalizer\cd.py", line 9, in <module>
ModuleNotFoundError: No module named 'charset_normalizer.md__mypyc'

**Comment by receyuki** [comment]
Check this out #13. You may need to whitelist the app in your antivirus.

**Comment by Deckard9999** [comment]
> Check this out #13. You may need to whitelist the app in your antivirus.

I read the previous message, before posting, as I wrote, I already set the app in the whitelist but didnt work anymore (and I cant understand why, being I used it by long time).
tnx for ur patience (and for the app)

**Comment by receyuki** [comment]
I have no idea how to solve it. The reason for the error is that some modules in the exe have been quarantined/deleted, which can only be caused by the antivirus.

**Comment by Deckard9999** [comment]
> I have no idea how to solve it. The reason for the error is that some modules in the exe have been quarantined/deleted, which can only be caused by the antivirus.

tnx for your effort anyway. is a pity couse sometimes I work on png without having SD opened and cant read prompt anymore.
hope in a better future...

**Comment by receyuki** [comment]
Another option is to use [the instruction for Linux users](https://github.com/receyuki/stable-diffusion-prompt-reader#for-linux-users-not-regularly-tested) to use this app.

**Comment by Deckard9999** [comment]
very kind of you but I promise myself not to touch code or compiling or everything else related again :-P
